[tool.poetry]
name = "academic-project"
version = "0.1.0"
description = "Projeto acadêmico para matéria de Desenvolvimento rápido em Python"
authors = ["Your Name <you@example.com>"]
license = "Unlicense"
readme = "README.md"
packages = [{include = "academic"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
